"""init schema

Revision ID: 4b0bfd0900bd
Revises: 
Create Date: 2026-06-22 14:14:41.271771
"""
from alembic import op
import sqlalchemy as sa


revision = '4b0bfd0900bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('key_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('scopes', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key_id')
    )
    op.create_index(op.f('ix_api_key_token'), 'api_key', ['token'], unique=True)
    op.create_table('app_user',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('allowed_views', sa.String(), nullable=False),
    sa.Column('permissions', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_app_user_username'), 'app_user', ['username'], unique=True)
    op.create_table('audit_log',
    sa.Column('audit_id', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('actor_role', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prev_hash', sa.String(), nullable=True),
    sa.Column('entry_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_seq'), 'audit_log', ['seq'], unique=False)
    op.create_index(op.f('ix_audit_log_ts'), 'audit_log', ['ts'], unique=False)
    op.create_table('bottle_record',
    sa.Column('bottle_id', sa.String(), nullable=False),
    sa.Column('bottle_code', sa.String(), nullable=False),
    sa.Column('filter_code', sa.String(), nullable=True),
    sa.Column('bottle_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('beer_type', sa.String(), nullable=False),
    sa.Column('lot_no', sa.String(), nullable=True),
    sa.Column('v_cap_chiet_hl', sa.Float(), nullable=False),
    sa.Column('from_bbt', sa.String(), nullable=True),
    sa.Column('line', sa.String(), nullable=True),
    sa.Column('ca1', sa.Float(), nullable=False),
    sa.Column('ca2', sa.Float(), nullable=False),
    sa.Column('ca3', sa.Float(), nullable=False),
    sa.Column('stocked', sa.Boolean(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('has_indicators', sa.Boolean(), nullable=False),
    sa.Column('has_nvl', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('bottle_id')
    )
    op.create_index(op.f('ix_bottle_record_bottle_code'), 'bottle_record', ['bottle_code'], unique=True)
    op.create_index(op.f('ix_bottle_record_bottle_date'), 'bottle_record', ['bottle_date'], unique=False)
    op.create_index(op.f('ix_bottle_record_filter_code'), 'bottle_record', ['filter_code'], unique=False)
    op.create_index(op.f('ix_bottle_record_from_bbt'), 'bottle_record', ['from_bbt'], unique=False)
    op.create_table('brew_record',
    sa.Column('brew_id', sa.String(), nullable=False),
    sa.Column('brew_code', sa.String(), nullable=False),
    sa.Column('brew_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('wort_type', sa.String(), nullable=False),
    sa.Column('volume_hl', sa.Float(), nullable=False),
    sa.Column('original_extract', sa.Float(), nullable=True),
    sa.Column('plato', sa.Float(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('brew_id')
    )
    op.create_index(op.f('ix_brew_record_brew_code'), 'brew_record', ['brew_code'], unique=True)
    op.create_index(op.f('ix_brew_record_brew_date'), 'brew_record', ['brew_date'], unique=False)
    op.create_table('deviation',
    sa.Column('deviation_id', sa.String(), nullable=False),
    sa.Column('deviation_code', sa.String(), nullable=False),
    sa.Column('scope_type', sa.String(), nullable=False),
    sa.Column('scope_id', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('investigation', sa.String(), nullable=True),
    sa.Column('disposition', sa.String(), nullable=True),
    sa.Column('opened_by', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('deviation_id')
    )
    op.create_index(op.f('ix_deviation_deviation_code'), 'deviation', ['deviation_code'], unique=True)
    op.create_index(op.f('ix_deviation_scope_id'), 'deviation', ['scope_id'], unique=False)
    op.create_table('ebr_snapshot',
    sa.Column('snap_id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('snapshot_version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('locked_by', sa.String(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('snap_id')
    )
    op.create_index(op.f('ix_ebr_snapshot_batch_id'), 'ebr_snapshot', ['batch_id'], unique=False)
    op.create_table('energy_area',
    sa.Column('area_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('area_id')
    )
    op.create_index(op.f('ix_energy_area_code'), 'energy_area', ['code'], unique=True)
    op.create_table('energy_group',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_index(op.f('ix_energy_group_code'), 'energy_group', ['code'], unique=True)
    op.create_table('equipment',
    sa.Column('equipment_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('eq_type', sa.String(), nullable=True),
    sa.Column('system', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('equipment_id')
    )
    op.create_index(op.f('ix_equipment_code'), 'equipment', ['code'], unique=True)
    op.create_table('esignature',
    sa.Column('sig_id', sa.String(), nullable=False),
    sa.Column('scope_type', sa.String(), nullable=False),
    sa.Column('scope_id', sa.String(), nullable=False),
    sa.Column('meaning', sa.String(), nullable=False),
    sa.Column('signed_by', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sig_id')
    )
    op.create_index(op.f('ix_esignature_scope_id'), 'esignature', ['scope_id'], unique=False)
    op.create_index(op.f('ix_esignature_scope_type'), 'esignature', ['scope_type'], unique=False)
    op.create_table('ferment_record',
    sa.Column('ferment_id', sa.String(), nullable=False),
    sa.Column('lm_code', sa.String(), nullable=False),
    sa.Column('brew_code', sa.String(), nullable=True),
    sa.Column('brew_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kt_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('batch_numbers', sa.String(), nullable=True),
    sa.Column('wort_type', sa.String(), nullable=False),
    sa.Column('yeast_gen', sa.String(), nullable=True),
    sa.Column('tank_lm', sa.String(), nullable=False),
    sa.Column('volume_hl', sa.Float(), nullable=False),
    sa.Column('on_hand_cct', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('ferment_days', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ferment_id')
    )
    op.create_index(op.f('ix_ferment_record_brew_code'), 'ferment_record', ['brew_code'], unique=False)
    op.create_index(op.f('ix_ferment_record_lm_code'), 'ferment_record', ['lm_code'], unique=True)
    op.create_index(op.f('ix_ferment_record_tank_lm'), 'ferment_record', ['tank_lm'], unique=False)
    op.create_table('filter_record',
    sa.Column('filter_id', sa.String(), nullable=False),
    sa.Column('filter_code', sa.String(), nullable=False),
    sa.Column('brew_code', sa.String(), nullable=True),
    sa.Column('lot_loc', sa.String(), nullable=True),
    sa.Column('filter_phoi_code', sa.String(), nullable=True),
    sa.Column('filter_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filter_type', sa.String(), nullable=False),
    sa.Column('wort_type', sa.String(), nullable=True),
    sa.Column('from_cct', sa.String(), nullable=True),
    sa.Column('v_dich_hl', sa.Float(), nullable=False),
    sa.Column('beer_type', sa.String(), nullable=False),
    sa.Column('v_beer_hl', sa.Float(), nullable=False),
    sa.Column('to_bbt', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('on_hand_bbt', sa.Float(), nullable=False),
    sa.Column('has_indicators', sa.Boolean(), nullable=False),
    sa.Column('has_nvl', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('filter_id')
    )
    op.create_index(op.f('ix_filter_record_filter_code'), 'filter_record', ['filter_code'], unique=True)
    op.create_index(op.f('ix_filter_record_filter_date'), 'filter_record', ['filter_date'], unique=False)
    op.create_index(op.f('ix_filter_record_to_bbt'), 'filter_record', ['to_bbt'], unique=False)
    op.create_table('genealogy_edge',
    sa.Column('edge_id', sa.String(), nullable=False),
    sa.Column('from_type', sa.String(), nullable=False),
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_type', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.Column('relation', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('uom', sa.String(), nullable=True),
    sa.Column('source_event', sa.String(), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('edge_id')
    )
    op.create_index(op.f('ix_genealogy_edge_from_id'), 'genealogy_edge', ['from_id'], unique=False)
    op.create_index(op.f('ix_genealogy_edge_to_id'), 'genealogy_edge', ['to_id'], unique=False)
    op.create_table('historian_point',
    sa.Column('point_id', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('quality', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('point_id')
    )
    op.create_index('ix_hist_tag_ts', 'historian_point', ['tag', 'ts'], unique=False)
    op.create_index(op.f('ix_historian_point_tag'), 'historian_point', ['tag'], unique=False)
    op.create_index(op.f('ix_historian_point_ts'), 'historian_point', ['ts'], unique=False)
    op.create_table('material',
    sa.Column('material_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('uom', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('material_id')
    )
    op.create_index(op.f('ix_material_code'), 'material', ['code'], unique=True)
    op.create_table('material_receipt',
    sa.Column('receipt_id', sa.String(), nullable=False),
    sa.Column('mskt', sa.String(), nullable=False),
    sa.Column('receipt_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('material_name', sa.String(), nullable=False),
    sa.Column('lot_pm', sa.String(), nullable=True),
    sa.Column('lot_kcs', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('uom', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('has_indicators', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('receipt_id')
    )
    op.create_index(op.f('ix_material_receipt_mskt'), 'material_receipt', ['mskt'], unique=False)
    op.create_index(op.f('ix_material_receipt_receipt_date'), 'material_receipt', ['receipt_date'], unique=False)
    op.create_table('oee_record',
    sa.Column('oee_id', sa.String(), nullable=False),
    sa.Column('line', sa.String(), nullable=False),
    sa.Column('shift', sa.String(), nullable=False),
    sa.Column('shift_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_time_min', sa.Float(), nullable=False),
    sa.Column('downtime_min', sa.Float(), nullable=False),
    sa.Column('ideal_rate_per_min', sa.Float(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('good_count', sa.Integer(), nullable=False),
    sa.Column('downtime_reasons', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('oee_id')
    )
    op.create_index(op.f('ix_oee_record_line'), 'oee_record', ['line'], unique=False)
    op.create_index(op.f('ix_oee_record_shift_date'), 'oee_record', ['shift_date'], unique=False)
    op.create_table('product',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('uom', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_product_code'), 'product', ['code'], unique=True)
    op.create_table('quality_result',
    sa.Column('result_id', sa.String(), nullable=False),
    sa.Column('sample_id', sa.String(), nullable=False),
    sa.Column('scope_type', sa.String(), nullable=False),
    sa.Column('scope_id', sa.String(), nullable=False),
    sa.Column('parameter', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('instrument', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('lower_limit', sa.Float(), nullable=True),
    sa.Column('upper_limit', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('recorded_by', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index(op.f('ix_quality_result_sample_id'), 'quality_result', ['sample_id'], unique=False)
    op.create_index(op.f('ix_quality_result_scope_id'), 'quality_result', ['scope_id'], unique=False)
    op.create_table('spare_part',
    sa.Column('part_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('uom', sa.String(), nullable=False),
    sa.Column('stock', sa.Float(), nullable=False),
    sa.Column('stock_min', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('part_id')
    )
    op.create_index(op.f('ix_spare_part_code'), 'spare_part', ['code'], unique=True)
    op.create_table('stage_indicator',
    sa.Column('indicator_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('scope_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('value_text', sa.String(), nullable=True),
    sa.Column('warning', sa.String(), nullable=True),
    sa.Column('analyst', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('indicator_id')
    )
    op.create_index(op.f('ix_stage_indicator_scope_code'), 'stage_indicator', ['scope_code'], unique=False)
    op.create_index(op.f('ix_stage_indicator_stage'), 'stage_indicator', ['stage'], unique=False)
    op.create_table('user_session',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_user_session_expires_at'), 'user_session', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_session_user_id'), 'user_session', ['user_id'], unique=False)
    op.create_table('webhook',
    sa.Column('webhook_id', sa.String(), nullable=False),
    sa.Column('target_url', sa.String(), nullable=False),
    sa.Column('event_types', sa.String(), nullable=False),
    sa.Column('secret', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('webhook_id')
    )
    op.create_table('yeast_lot',
    sa.Column('yeast_lot_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('strain', sa.String(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('source_tank', sa.String(), nullable=True),
    sa.Column('source_batch_id', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('uom', sa.String(), nullable=False),
    sa.Column('viability', sa.Float(), nullable=True),
    sa.Column('vitality', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('harvest_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('yeast_lot_id')
    )
    op.create_index(op.f('ix_yeast_lot_code'), 'yeast_lot', ['code'], unique=True)
    op.create_table('calibration',
    sa.Column('calib_id', sa.String(), nullable=False),
    sa.Column('equipment_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('calib_type', sa.String(), nullable=False),
    sa.Column('last_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('interval_months', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], ),
    sa.PrimaryKeyConstraint('calib_id')
    )
    op.create_index(op.f('ix_calibration_due_date'), 'calibration', ['due_date'], unique=False)
    op.create_index(op.f('ix_calibration_equipment_id'), 'calibration', ['equipment_id'], unique=False)
    op.create_table('energy_reading',
    sa.Column('reading_id', sa.String(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('area_id', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['energy_area.area_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['energy_group.group_id'], ),
    sa.PrimaryKeyConstraint('reading_id'),
    sa.UniqueConstraint('day', 'group_id', 'area_id', name='uq_energy_daily')
    )
    op.create_index(op.f('ix_energy_reading_day'), 'energy_reading', ['day'], unique=False)
    op.create_index(op.f('ix_energy_reading_group_id'), 'energy_reading', ['group_id'], unique=False)
    op.create_table('incident',
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('incident_code', sa.String(), nullable=False),
    sa.Column('equipment_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('downtime_min', sa.Float(), nullable=False),
    sa.Column('reported_by', sa.String(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], ),
    sa.PrimaryKeyConstraint('incident_id')
    )
    op.create_index(op.f('ix_incident_equipment_id'), 'incident', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_incident_incident_code'), 'incident', ['incident_code'], unique=True)
    op.create_table('maintenance_plan',
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('equipment_id', sa.String(), nullable=False),
    sa.Column('plan_type', sa.String(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], ),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index(op.f('ix_maintenance_plan_equipment_id'), 'maintenance_plan', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_maintenance_plan_scheduled_date'), 'maintenance_plan', ['scheduled_date'], unique=False)
    op.create_table('material_lot',
    sa.Column('lot_id', sa.String(), nullable=False),
    sa.Column('lot_code', sa.String(), nullable=False),
    sa.Column('material_id', sa.String(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('lot_type', sa.String(), nullable=False),
    sa.Column('supplier_lot', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('uom', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['material.material_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('lot_id')
    )
    op.create_index(op.f('ix_material_lot_lot_code'), 'material_lot', ['lot_code'], unique=True)
    op.create_table('production_order',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('order_code', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('planned_qty', sa.Float(), nullable=False),
    sa.Column('uom', sa.String(), nullable=False),
    sa.Column('due_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_production_order_order_code'), 'production_order', ['order_code'], unique=True)
    op.create_table('recipe',
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    op.create_index(op.f('ix_recipe_code'), 'recipe', ['code'], unique=True)
    op.create_table('recipe_version',
    sa.Column('version_id', sa.String(), nullable=False),
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('base_qty', sa.Float(), nullable=False),
    sa.Column('base_uom', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('materials', sa.JSON(), nullable=False),
    sa.Column('quality_checks', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.recipe_id'], ),
    sa.PrimaryKeyConstraint('version_id'),
    sa.UniqueConstraint('recipe_id', 'version_no', name='uq_recipe_version')
    )
    op.create_index(op.f('ix_recipe_version_recipe_id'), 'recipe_version', ['recipe_id'], unique=False)
    op.create_table('stock_movement',
    sa.Column('movement_id', sa.String(), nullable=False),
    sa.Column('movement_type', sa.String(), nullable=False),
    sa.Column('material_id', sa.String(), nullable=True),
    sa.Column('lot_id', sa.String(), nullable=True),
    sa.Column('lot_code', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('uom', sa.String(), nullable=False),
    sa.Column('location_from', sa.String(), nullable=True),
    sa.Column('location_to', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('ref_doc', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['material_lot.lot_id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.material_id'], ),
    sa.PrimaryKeyConstraint('movement_id')
    )
    op.create_index(op.f('ix_stock_movement_lot_id'), 'stock_movement', ['lot_id'], unique=False)
    op.create_index(op.f('ix_stock_movement_material_id'), 'stock_movement', ['material_id'], unique=False)
    op.create_index(op.f('ix_stock_movement_movement_type'), 'stock_movement', ['movement_type'], unique=False)
    op.create_index(op.f('ix_stock_movement_ts'), 'stock_movement', ['ts'], unique=False)
    op.create_table('batch_execution',
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('batch_code', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('work_order_id', sa.String(), nullable=True),
    sa.Column('recipe_version_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('quality_status', sa.String(), nullable=False),
    sa.Column('planned_qty', sa.Float(), nullable=False),
    sa.Column('actual_qty', sa.Float(), nullable=True),
    sa.Column('uom', sa.String(), nullable=False),
    sa.Column('recipe_snapshot', sa.JSON(), nullable=False),
    sa.Column('actuals', sa.JSON(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ebr_locked', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['production_order.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['recipe_version_id'], ['recipe_version.version_id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_index(op.f('ix_batch_execution_batch_code'), 'batch_execution', ['batch_code'], unique=True)
    op.create_index(op.f('ix_batch_execution_order_id'), 'batch_execution', ['order_id'], unique=False)
    op.create_index(op.f('ix_batch_execution_work_order_id'), 'batch_execution', ['work_order_id'], unique=False)
    op.create_table('work_order',
    sa.Column('wo_id', sa.String(), nullable=False),
    sa.Column('wo_code', sa.String(), nullable=False),
    sa.Column('production_order_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('recipe_version_id', sa.String(), nullable=True),
    sa.Column('planned_qty', sa.Float(), nullable=False),
    sa.Column('uom', sa.String(), nullable=False),
    sa.Column('line', sa.String(), nullable=True),
    sa.Column('shift', sa.String(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_order.order_id'], ),
    sa.ForeignKeyConstraint(['recipe_version_id'], ['recipe_version.version_id'], ),
    sa.PrimaryKeyConstraint('wo_id')
    )
    op.create_index(op.f('ix_work_order_line'), 'work_order', ['line'], unique=False)
    op.create_index(op.f('ix_work_order_production_order_id'), 'work_order', ['production_order_id'], unique=False)
    op.create_index(op.f('ix_work_order_scheduled_date'), 'work_order', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_work_order_status'), 'work_order', ['status'], unique=False)
    op.create_index(op.f('ix_work_order_wo_code'), 'work_order', ['wo_code'], unique=True)
    op.create_table('chemical_usage',
    sa.Column('usage_id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('chemical', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('uom', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch_execution.batch_id'], ),
    sa.PrimaryKeyConstraint('usage_id')
    )
    op.create_index(op.f('ix_chemical_usage_batch_id'), 'chemical_usage', ['batch_id'], unique=False)
    op.create_table('process_reading',
    sa.Column('reading_id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('parameter', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quality', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch_execution.batch_id'], ),
    sa.PrimaryKeyConstraint('reading_id')
    )
    op.create_index(op.f('ix_process_reading_batch_id'), 'process_reading', ['batch_id'], unique=False)
    op.create_index(op.f('ix_process_reading_parameter'), 'process_reading', ['parameter'], unique=False)
    op.create_index(op.f('ix_process_reading_ts'), 'process_reading', ['ts'], unique=False)
    op.create_table('yeast_issue',
    sa.Column('issue_id', sa.String(), nullable=False),
    sa.Column('yeast_lot_id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('uom', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch_execution.batch_id'], ),
    sa.ForeignKeyConstraint(['yeast_lot_id'], ['yeast_lot.yeast_lot_id'], ),
    sa.PrimaryKeyConstraint('issue_id')
    )
    op.create_index(op.f('ix_yeast_issue_batch_id'), 'yeast_issue', ['batch_id'], unique=False)
    op.create_index(op.f('ix_yeast_issue_yeast_lot_id'), 'yeast_issue', ['yeast_lot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yeast_issue_yeast_lot_id'), table_name='yeast_issue')
    op.drop_index(op.f('ix_yeast_issue_batch_id'), table_name='yeast_issue')
    op.drop_table('yeast_issue')
    op.drop_index(op.f('ix_process_reading_ts'), table_name='process_reading')
    op.drop_index(op.f('ix_process_reading_parameter'), table_name='process_reading')
    op.drop_index(op.f('ix_process_reading_batch_id'), table_name='process_reading')
    op.drop_table('process_reading')
    op.drop_index(op.f('ix_chemical_usage_batch_id'), table_name='chemical_usage')
    op.drop_table('chemical_usage')
    op.drop_index(op.f('ix_work_order_wo_code'), table_name='work_order')
    op.drop_index(op.f('ix_work_order_status'), table_name='work_order')
    op.drop_index(op.f('ix_work_order_scheduled_date'), table_name='work_order')
    op.drop_index(op.f('ix_work_order_production_order_id'), table_name='work_order')
    op.drop_index(op.f('ix_work_order_line'), table_name='work_order')
    op.drop_table('work_order')
    op.drop_index(op.f('ix_batch_execution_work_order_id'), table_name='batch_execution')
    op.drop_index(op.f('ix_batch_execution_order_id'), table_name='batch_execution')
    op.drop_index(op.f('ix_batch_execution_batch_code'), table_name='batch_execution')
    op.drop_table('batch_execution')
    op.drop_index(op.f('ix_stock_movement_ts'), table_name='stock_movement')
    op.drop_index(op.f('ix_stock_movement_movement_type'), table_name='stock_movement')
    op.drop_index(op.f('ix_stock_movement_material_id'), table_name='stock_movement')
    op.drop_index(op.f('ix_stock_movement_lot_id'), table_name='stock_movement')
    op.drop_table('stock_movement')
    op.drop_index(op.f('ix_recipe_version_recipe_id'), table_name='recipe_version')
    op.drop_table('recipe_version')
    op.drop_index(op.f('ix_recipe_code'), table_name='recipe')
    op.drop_table('recipe')
    op.drop_index(op.f('ix_production_order_order_code'), table_name='production_order')
    op.drop_table('production_order')
    op.drop_index(op.f('ix_material_lot_lot_code'), table_name='material_lot')
    op.drop_table('material_lot')
    op.drop_index(op.f('ix_maintenance_plan_scheduled_date'), table_name='maintenance_plan')
    op.drop_index(op.f('ix_maintenance_plan_equipment_id'), table_name='maintenance_plan')
    op.drop_table('maintenance_plan')
    op.drop_index(op.f('ix_incident_incident_code'), table_name='incident')
    op.drop_index(op.f('ix_incident_equipment_id'), table_name='incident')
    op.drop_table('incident')
    op.drop_index(op.f('ix_energy_reading_group_id'), table_name='energy_reading')
    op.drop_index(op.f('ix_energy_reading_day'), table_name='energy_reading')
    op.drop_table('energy_reading')
    op.drop_index(op.f('ix_calibration_equipment_id'), table_name='calibration')
    op.drop_index(op.f('ix_calibration_due_date'), table_name='calibration')
    op.drop_table('calibration')
    op.drop_index(op.f('ix_yeast_lot_code'), table_name='yeast_lot')
    op.drop_table('yeast_lot')
    op.drop_table('webhook')
    op.drop_index(op.f('ix_user_session_user_id'), table_name='user_session')
    op.drop_index(op.f('ix_user_session_expires_at'), table_name='user_session')
    op.drop_table('user_session')
    op.drop_index(op.f('ix_stage_indicator_stage'), table_name='stage_indicator')
    op.drop_index(op.f('ix_stage_indicator_scope_code'), table_name='stage_indicator')
    op.drop_table('stage_indicator')
    op.drop_index(op.f('ix_spare_part_code'), table_name='spare_part')
    op.drop_table('spare_part')
    op.drop_index(op.f('ix_quality_result_scope_id'), table_name='quality_result')
    op.drop_index(op.f('ix_quality_result_sample_id'), table_name='quality_result')
    op.drop_table('quality_result')
    op.drop_index(op.f('ix_product_code'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_oee_record_shift_date'), table_name='oee_record')
    op.drop_index(op.f('ix_oee_record_line'), table_name='oee_record')
    op.drop_table('oee_record')
    op.drop_index(op.f('ix_material_receipt_receipt_date'), table_name='material_receipt')
    op.drop_index(op.f('ix_material_receipt_mskt'), table_name='material_receipt')
    op.drop_table('material_receipt')
    op.drop_index(op.f('ix_material_code'), table_name='material')
    op.drop_table('material')
    op.drop_index(op.f('ix_historian_point_ts'), table_name='historian_point')
    op.drop_index(op.f('ix_historian_point_tag'), table_name='historian_point')
    op.drop_index('ix_hist_tag_ts', table_name='historian_point')
    op.drop_table('historian_point')
    op.drop_index(op.f('ix_genealogy_edge_to_id'), table_name='genealogy_edge')
    op.drop_index(op.f('ix_genealogy_edge_from_id'), table_name='genealogy_edge')
    op.drop_table('genealogy_edge')
    op.drop_index(op.f('ix_filter_record_to_bbt'), table_name='filter_record')
    op.drop_index(op.f('ix_filter_record_filter_date'), table_name='filter_record')
    op.drop_index(op.f('ix_filter_record_filter_code'), table_name='filter_record')
    op.drop_table('filter_record')
    op.drop_index(op.f('ix_ferment_record_tank_lm'), table_name='ferment_record')
    op.drop_index(op.f('ix_ferment_record_lm_code'), table_name='ferment_record')
    op.drop_index(op.f('ix_ferment_record_brew_code'), table_name='ferment_record')
    op.drop_table('ferment_record')
    op.drop_index(op.f('ix_esignature_scope_type'), table_name='esignature')
    op.drop_index(op.f('ix_esignature_scope_id'), table_name='esignature')
    op.drop_table('esignature')
    op.drop_index(op.f('ix_equipment_code'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_energy_group_code'), table_name='energy_group')
    op.drop_table('energy_group')
    op.drop_index(op.f('ix_energy_area_code'), table_name='energy_area')
    op.drop_table('energy_area')
    op.drop_index(op.f('ix_ebr_snapshot_batch_id'), table_name='ebr_snapshot')
    op.drop_table('ebr_snapshot')
    op.drop_index(op.f('ix_deviation_scope_id'), table_name='deviation')
    op.drop_index(op.f('ix_deviation_deviation_code'), table_name='deviation')
    op.drop_table('deviation')
    op.drop_index(op.f('ix_brew_record_brew_date'), table_name='brew_record')
    op.drop_index(op.f('ix_brew_record_brew_code'), table_name='brew_record')
    op.drop_table('brew_record')
    op.drop_index(op.f('ix_bottle_record_from_bbt'), table_name='bottle_record')
    op.drop_index(op.f('ix_bottle_record_filter_code'), table_name='bottle_record')
    op.drop_index(op.f('ix_bottle_record_bottle_date'), table_name='bottle_record')
    op.drop_index(op.f('ix_bottle_record_bottle_code'), table_name='bottle_record')
    op.drop_table('bottle_record')
    op.drop_index(op.f('ix_audit_log_ts'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_seq'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_app_user_username'), table_name='app_user')
    op.drop_table('app_user')
    op.drop_index(op.f('ix_api_key_token'), table_name='api_key')
    op.drop_table('api_key')
    # ### end Alembic commands ###
