"""depth subsystems + hardening + ai memory

Revision ID: 89f74fef30e3
Revises: 4b0bfd0900bd
Create Date: 2026-06-23 13:45:23.590253
"""
from alembic import op
import sqlalchemy as sa


revision = '89f74fef30e3'
down_revision = '4b0bfd0900bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_conversation',
    sa.Column('conv_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('conv_id')
    )
    op.create_index(op.f('ix_ai_conversation_username'), 'ai_conversation', ['username'], unique=False)
    op.create_table('capa',
    sa.Column('capa_id', sa.String(length=64), nullable=False),
    sa.Column('capa_code', sa.String(length=64), nullable=False),
    sa.Column('deviation_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('capa_type', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('root_cause', sa.String(length=255), nullable=True),
    sa.Column('action_plan', sa.String(length=255), nullable=True),
    sa.Column('effectiveness', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('opened_by', sa.String(length=255), nullable=True),
    sa.Column('closed_by', sa.String(length=255), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('capa_id')
    )
    op.create_index(op.f('ix_capa_capa_code'), 'capa', ['capa_code'], unique=True)
    op.create_index(op.f('ix_capa_deviation_id'), 'capa', ['deviation_id'], unique=False)
    op.create_table('lims_sample',
    sa.Column('sample_id', sa.String(length=64), nullable=False),
    sa.Column('sample_code', sa.String(length=64), nullable=False),
    sa.Column('scope_type', sa.String(length=255), nullable=False),
    sa.Column('scope_id', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('test_set', sa.String(length=255), nullable=True),
    sa.Column('registered_by', sa.String(length=255), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('sample_id')
    )
    op.create_index(op.f('ix_lims_sample_sample_code'), 'lims_sample', ['sample_code'], unique=True)
    op.create_index(op.f('ix_lims_sample_scope_id'), 'lims_sample', ['scope_id'], unique=False)
    op.create_table('qc_parameter',
    sa.Column('param_id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=255), nullable=True),
    sa.Column('target', sa.Float(), nullable=True),
    sa.Column('usl', sa.Float(), nullable=True),
    sa.Column('lsl', sa.Float(), nullable=True),
    sa.Column('stage', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('param_id')
    )
    op.create_index(op.f('ix_qc_parameter_code'), 'qc_parameter', ['code'], unique=True)
    op.create_table('recipe_change',
    sa.Column('change_id', sa.String(length=64), nullable=False),
    sa.Column('change_code', sa.String(length=64), nullable=False),
    sa.Column('recipe_id', sa.String(length=64), nullable=False),
    sa.Column('version_id', sa.String(length=64), nullable=False),
    sa.Column('from_version_id', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('diff', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('change_id')
    )
    op.create_index(op.f('ix_recipe_change_change_code'), 'recipe_change', ['change_code'], unique=True)
    op.create_index(op.f('ix_recipe_change_recipe_id'), 'recipe_change', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_recipe_change_version_id'), 'recipe_change', ['version_id'], unique=False)
    op.create_table('ai_message',
    sa.Column('msg_id', sa.String(length=64), nullable=False),
    sa.Column('conv_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tools_used', sa.String(length=255), nullable=True),
    sa.Column('mode', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conv_id'], ['ai_conversation.conv_id'], ),
    sa.PrimaryKeyConstraint('msg_id')
    )
    op.create_index(op.f('ix_ai_message_conv_id'), 'ai_message', ['conv_id'], unique=False)
    op.create_table('downtime_event',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('line', sa.String(length=255), nullable=False),
    sa.Column('equipment_id', sa.String(length=64), nullable=True),
    sa.Column('shift', sa.String(length=255), nullable=False),
    sa.Column('shift_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason_group', sa.String(length=255), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('reason_label', sa.String(length=255), nullable=True),
    sa.Column('loss_category', sa.String(length=255), nullable=False),
    sa.Column('minutes', sa.Float(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.String(length=255), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_downtime_event_equipment_id'), 'downtime_event', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_downtime_event_line'), 'downtime_event', ['line'], unique=False)
    op.create_index(op.f('ix_downtime_event_reason_code'), 'downtime_event', ['reason_code'], unique=False)
    op.create_index(op.f('ix_downtime_event_reason_group'), 'downtime_event', ['reason_group'], unique=False)
    op.create_index(op.f('ix_downtime_event_shift_date'), 'downtime_event', ['shift_date'], unique=False)
    op.create_table('batch_yield_actual',
    sa.Column('yield_id', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('step_key', sa.String(length=255), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('input_qty', sa.Float(), nullable=False),
    sa.Column('output_qty', sa.Float(), nullable=False),
    sa.Column('uom', sa.String(length=255), nullable=False),
    sa.Column('expected_pct', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.String(length=255), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch_execution.batch_id'], ),
    sa.PrimaryKeyConstraint('yield_id')
    )
    op.create_index(op.f('ix_batch_yield_actual_batch_id'), 'batch_yield_actual', ['batch_id'], unique=False)
    op.create_table('dispense',
    sa.Column('dispense_id', sa.String(length=64), nullable=False),
    sa.Column('dispense_code', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch_execution.batch_id'], ),
    sa.PrimaryKeyConstraint('dispense_id')
    )
    op.create_index(op.f('ix_dispense_batch_id'), 'dispense', ['batch_id'], unique=False)
    op.create_index(op.f('ix_dispense_dispense_code'), 'dispense', ['dispense_code'], unique=True)
    op.create_table('dispense_line',
    sa.Column('line_id', sa.String(length=64), nullable=False),
    sa.Column('dispense_id', sa.String(length=64), nullable=False),
    sa.Column('material_code', sa.String(length=64), nullable=False),
    sa.Column('lot_id', sa.String(length=64), nullable=True),
    sa.Column('lot_code', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('uom', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dispense_id'], ['dispense.dispense_id'], ),
    sa.PrimaryKeyConstraint('line_id')
    )
    op.create_index(op.f('ix_dispense_line_dispense_id'), 'dispense_line', ['dispense_id'], unique=False)
    op.create_index(op.f('ix_dispense_line_material_code'), 'dispense_line', ['material_code'], unique=False)
    # server_default cho cột NOT NULL: SQLite không cho thêm cột NOT NULL thiếu default,
    # và Postgres cần default để điền cho các hàng đã có khi nâng cấp prod đang chạy.
    op.add_column('app_user', sa.Column('scope_lines', sa.String(length=255), nullable=False, server_default="*"))
    op.add_column('app_user', sa.Column('scope_areas', sa.String(length=255), nullable=False, server_default="*"))
    op.add_column('app_user', sa.Column('scope_qc', sa.String(length=255), nullable=False, server_default="*"))
    op.add_column('app_user', sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.drop_index('ix_audit_log_seq', table_name='audit_log')
    op.create_index(op.f('ix_audit_log_seq'), 'audit_log', ['seq'], unique=True)
    op.add_column('recipe_version', sa.Column('yield_steps', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
    op.add_column('recipe_version', sa.Column('change_reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_version', 'change_reason')
    op.drop_column('recipe_version', 'yield_steps')
    op.drop_index(op.f('ix_audit_log_seq'), table_name='audit_log')
    op.create_index('ix_audit_log_seq', 'audit_log', ['seq'], unique=False)
    op.drop_column('app_user', 'must_change_password')
    op.drop_column('app_user', 'scope_qc')
    op.drop_column('app_user', 'scope_areas')
    op.drop_column('app_user', 'scope_lines')
    op.drop_index(op.f('ix_dispense_line_material_code'), table_name='dispense_line')
    op.drop_index(op.f('ix_dispense_line_dispense_id'), table_name='dispense_line')
    op.drop_table('dispense_line')
    op.drop_index(op.f('ix_dispense_dispense_code'), table_name='dispense')
    op.drop_index(op.f('ix_dispense_batch_id'), table_name='dispense')
    op.drop_table('dispense')
    op.drop_index(op.f('ix_batch_yield_actual_batch_id'), table_name='batch_yield_actual')
    op.drop_table('batch_yield_actual')
    op.drop_index(op.f('ix_downtime_event_shift_date'), table_name='downtime_event')
    op.drop_index(op.f('ix_downtime_event_reason_group'), table_name='downtime_event')
    op.drop_index(op.f('ix_downtime_event_reason_code'), table_name='downtime_event')
    op.drop_index(op.f('ix_downtime_event_line'), table_name='downtime_event')
    op.drop_index(op.f('ix_downtime_event_equipment_id'), table_name='downtime_event')
    op.drop_table('downtime_event')
    op.drop_index(op.f('ix_ai_message_conv_id'), table_name='ai_message')
    op.drop_table('ai_message')
    op.drop_index(op.f('ix_recipe_change_version_id'), table_name='recipe_change')
    op.drop_index(op.f('ix_recipe_change_recipe_id'), table_name='recipe_change')
    op.drop_index(op.f('ix_recipe_change_change_code'), table_name='recipe_change')
    op.drop_table('recipe_change')
    op.drop_index(op.f('ix_qc_parameter_code'), table_name='qc_parameter')
    op.drop_table('qc_parameter')
    op.drop_index(op.f('ix_lims_sample_scope_id'), table_name='lims_sample')
    op.drop_index(op.f('ix_lims_sample_sample_code'), table_name='lims_sample')
    op.drop_table('lims_sample')
    op.drop_index(op.f('ix_capa_deviation_id'), table_name='capa')
    op.drop_index(op.f('ix_capa_capa_code'), table_name='capa')
    op.drop_table('capa')
    op.drop_index(op.f('ix_ai_conversation_username'), table_name='ai_conversation')
    op.drop_table('ai_conversation')
    # ### end Alembic commands ###
